### ISSUE TITLE
TypeError: this.constructor.adapter.id is not a function

### ISSUE THREAD

**Issue by hult** [confetti/yayson#33]
I have a presenter like this (ES6)

    import yayson from 'yayson'
    const y = yayson({adapter: 'default'})
    const Presenter = y.Presenter

    export class MyPresenter extends Presenter {
      render(instanceOrCollection, options) {
        var output = super.render(instanceOrCollection, options)  // this is line 24 referred to below
        // ...
      }
    }

In 2.0.3, this works fine. In 2.0.5, I get

    TypeError: this.constructor.adapter.id is not a function
      at MyPresenter.Presenter.id (node_modules/yayson/lib/yayson/presenter.js:31:39)
      at MyPresenter.Presenter.toJSON (node_modules/yayson/lib/yayson/presenter.js:152:20)
      at MyPresenter.Presenter.render (node_modules/yayson/lib/yayson/presenter.js:202:21)
      at MyPresenter.render (app/api/jsonapi.js:24:9)

**Comment by jede** [comment]
Sorry! This should be fixed in 2.0.6. I also added some docs on how to add your own adapters.

**Comment by hult** [comment]
Can confirm everything works now, thanks! :)
